### ISSUE TITLE
Peana volcà

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#318]
Per no haver d'amagar una peana sota el volcà.

**Comment by emabece** [comment]
When a Scarabeus deploys into a crater (VolcanoSpot) this should happen:

- Place in the spot and play the particle system 'P_CraterDeploying'
- Play slower the transforming animation of the Scarabeus
- Play a drilling and rocks sound effect

*Discuss whether this process must happen each time the Scarabeus deploys into a volcano, only the first time for each VolcanoSpot or only one time
