### ISSUE TITLE
Fallen rocks & explosion decals

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#552]
Where rocks have fallen we need some smaller dust and little rocks around the place. It looks too clean. Maybe a decal would do.

**Comment by emabece** [comment]
Materials for decals have been created. Decal_Dust_M and Decal_Explosion_M will work for decals placed just after some rocks falling or bombs exploding.

**Comment by alexei-anticto** [comment]
Added fallen rock decals and explosion decals limited in number with garbage collection and dissolve.
