### ISSUE TITLE
Idees per "achievements"

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#572]
La idea és que la meitat siguin assolibles només passant-te el joc, però l'altre meitat requereixin d'esforç extra.
- [x] "Your first contribution" a l'ensorrar l'ascensor.
- [x] "Rescue Garcia" al destruir les roques del nivell Bascules.
- [ ] "Optimum Escher" si es resol l'escher amb menys de XXX recursos.

**Comment by alexei-anticto** [comment]
-[ ] Un achievement en cada nivell qual te'l passes amb la puntuació mínima que coneixem.
-[ ] Un achievement quan completes tots els nivells amb puntuació mínima.

**Comment by emabece** [comment]
- [ ] "Fast Scarabeus" si fas l'inici del survivors destrossant els Barrils
- [ ] "Keep calm and break boxes" passant-te el Magatzem sense fer servir explosius
- [ ] "Psycothic engineer" si algú destrossa totes les caixes de tots els nivells
- [ ] "Myopic engineer" si es posa la rampa del Peanes malament
- [ ] "Cleaning the path" després de trencar les roques del passadís del Silvia's
- [ ] "Patience is a virtue" el primer cop que algú fagi "restart level"

**Comment by jordirovira** [comment]
Bé! és un bon principi. el "Myopic engineer" sembla difícil de programar. El meu "Optimum Escher" queda subsumit en els de l'Alexei. Afegeixo: 
- [ ] "You are a good driller!"  quan fas venir el driller
Per mi ja els podem començar a programar.

**Comment by alexei-anticto** [comment]
Potser caldria tenir el disseny de les icones dels achievements més bàsics primer.

**Comment by jordirovira** [comment]
- [ ] Recollir tots els power up de vapor en el "low pressure"

**Comment by emabece** [comment]
[ ] - Quan reculls a la Garcia al teu Scarabeus
[ ] - "Salt de l'àngel" si algú es tira (i no mor) des del punt més alt del Low Pressure cap a la sortida
[ ] - "Cleaning the path II" quan trenques les roques del Coop Platformer*
[ ] - "The corpse of Valuska's Driller" al final del Low Pressure

*Quan desbloqueges a la Garcia al Bascules, pot ser un altre Cleaning the path

**Comment by emabece** [comment]
First 7 achievement images have been created:

Z:\Projectes\Steamroll\Art\Achievements - here there is a MockupSteam.jpg that shows the sequence of achievements and inside PNG folder there are two PNG for each achievement.

**Comment by alexei-anticto** [comment]
![corpsedriller_bw](https://cloud.githubusercontent.com/assets/7813974/11979892/268c0f3e-a997-11e5-8512-2b30155ba00e.png)
![corpsedriller_c](https://cloud.githubusercontent.com/assets/7813974/11979891/268bcdbc-a997-11e5-9cc3-28010fef8a84.png)
![elevator_bw](https://cloud.githubusercontent.com/assets/7813974/11979893/268ef442-a997-11e5-9328-66d356110e08.png)
![elevator_c](https://cloud.githubusercontent.com/assets/7813974/11979895/269292dc-a997-11e5-9c25-cec4206dec34.png)
![rockplatformer_bw](https://cloud.githubusercontent.com/assets/7813974/11979894/26906124-a997-11e5-8c05-570075de17f9.png)
![rockplatformer_c](https://cloud.githubusercontent.com/assets/7813974/11979901/26ad30ba-a997-11e5-9f67-2562e49cc096.png)
![silviascorridor_bw](https://cloud.githubusercontent.com/assets/7813974/11979896/26a28278-a997-11e5-9a0a-a28e3cae96a0.png)
![silviascorridor_c](https://cloud.githubusercontent.com/assets/7813974/11979897/26a3aaa4-a997-11e5-8f54-67e845913736.png)
![backdriller_bw](https://cloud.githubusercontent.com/assets/7813974/11979898/26a5b66e-a997-11e5-8b5f-4c9392ff7d12.png)
![backdriller_c](https://cloud.githubusercontent.com/assets/7813974/11979899/26a9f1ca-a997-11e5-8083-b834eacce588.png)
![basculesgarcia_bw](https://cloud.githubusercontent.com/assets/7813974/11979900/26aa6b6e-a997-11e5-9ba1-db475621a318.png)
![basculesgarcia_c](https://cloud.githubusercontent.com/assets/7813974/11979902/26b90e08-a997-11e5-8911-51c0b626aa6a.png)
![characterstogether_bw](https://cloud.githubusercontent.com/assets/7813974/11979903/26bc0a40-a997-11e5-8936-d4c12da90fac.png)
![characterstogether_c](https://cloud.githubusercontent.com/assets/7813974/11979904/26bdf08a-a997-11e5-9021-82b1a957789e.png)

**Comment by emabece** [comment]
![mockupsteam](https://cloud.githubusercontent.com/assets/8545905/11994167/6c34035e-aa3a-11e5-94f5-521a5445cd02.jpg)

**Comment by alexei-anticto** [comment]
All the achievements in the mockup have already been implemented.

**Comment by emabece** [comment]
This basic achievements are a bit spoiler to the main plot. We should add more basic ones and hide the spoiler ones.
