### ISSUE TITLE
investigate what art is required for the loading spinner

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#633]

**Comment by alexei-anticto** [comment]
A movie file similar to the one in Content/Movies is needed.

The movie player doesn't work under linux or xbox one for the moment. I don't know about mac...

**Comment by jordirovira** [comment]
doncs haurem de buscar un mètode alternatiu, encara que sigui un widget animat més senzill... com una imatge rotant per codi o similar.

**Comment by jordirovira** [comment]
Aquest és crític i l'estat actual no ens val. Ara mateix o ho desactivem o ho arreglem per la #22. 
Alexei, es pot posar el vídeo sense que sigui fullscreen, en un video petit? Encara que sigui un gif animat o una textura animada com les de les partícules però en un widget? Textura 3D?
