### ISSUE TITLE
Duplicate PushTriggerButton BP with new meshes

### ISSUE THREAD

**Issue by emabece** [anticto/steamroll#669]
A copy of actual PushTriggerButton will have, instead of BT_Caixa and BT_Press meshes, BigButtonBody and BigButtonPress, with BigButton_M and BT_PressBig_M materials respectively assigned.

This new button will be mainly activated with Scarabeus (but no restricted to Steamballs)

*Note: Actual PushTriggerButton will always have now the BT_Light mesh, so this original BP will never have "Remove Light" parameter ON. OFF option has to be switched with new PushTriggerButton

**Comment by alexei-anticto** [comment]
Every button with light removed in the game needs to be checked.
