### ISSUE TITLE
Finish Driller level

### ISSUE THREAD

**Issue by emabece** [anticto/steamroll#690]
- [x] Configure DSpot on Driller (1 slot, 7 or 10 steamballs, no items, no activators)
- [x] Show "EndLevel" camera when Driller-part-puzzle starts (aka when leaving the 'regular' part)
- [x] Make Driller Camera responsive to Camera Blocking Volumes

**Comment by alexei-anticto** [comment]
- [ ] Remove camera jumps from driller intro.
