### ISSUE TITLE
Provar d'accelerar la nosta física x2

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#744]

**Comment by jordirovira** [comment]
sense que canvii el resultat

**Comment by alexei-anticto** [comment]
Easy to do, except for:

-Walls still deploy slowly and can break some puzzles, (3 buttons, the trap, etc).
-Gameplay steamballs (collapse and Valuska in driller) are crazy fast.

**Comment by alexei-anticto** [comment]
Commited code for testing the idea.
