### ISSUE TITLE
Implement new level menu design

### ISSUE THREAD

**Issue by emabece** [anticto/steamroll#759]
In Z:\Projectes\Steamroll\Art\Menu\Level_Menu\mockup there are some mockups and example image files to implement the design

**Comment by alexei-anticto** [comment]
![level_menu_mockup2](https://cloud.githubusercontent.com/assets/7813974/11865059/de091e40-a4a1-11e5-9918-fc1a317238c4.jpg)
![levelenigma](https://cloud.githubusercontent.com/assets/7813974/11865055/db57ef3c-a4a1-11e5-9a4a-19adc9b6c88c.png)
![levelexample](https://cloud.githubusercontent.com/assets/7813974/11865056/db5a7bd0-a4a1-11e5-9cb6-56986181d937.png)
![levelthumbnailexample](https://cloud.githubusercontent.com/assets/7813974/11865060/de0bb2ea-a4a1-11e5-8183-4962378ac109.png)
![roundempty](https://cloud.githubusercontent.com/assets/7813974/11865061/de0d6414-a4a1-11e5-858c-6ad1581f33a3.png)
![roundfull](https://cloud.githubusercontent.com/assets/7813974/11865062/de0d4448-a4a1-11e5-8f83-cd75ae6d7a0b.png)
![level_menu_mockup](https://cloud.githubusercontent.com/assets/7813974/11865063/de1a438c-a4a1-11e5-8d61-55500289bf5b.jpg)

**Comment by emabece** [comment]
Level images and thumbnails have been created and uploaded in:
Content/itemsMenu/LevelMenu/LevelImg and LevelThumbnails
