### ISSUE TITLE
Implement Pause Menu and Steamlog

### ISSUE THREAD

**Issue by emabece** [anticto/steamroll#760]

**Comment by emabece** [comment]
Z:\Projectes\Steamroll\Art\Menu\Pause_Menu\mockups

**Comment by alexei-anticto** [comment]
![controls](https://cloud.githubusercontent.com/assets/7813974/11865126/563a40ba-a4a2-11e5-8764-fe5efab774e4.jpg)
![pausesteamlog](https://cloud.githubusercontent.com/assets/7813974/11865128/563eab32-a4a2-11e5-9e76-ece2a7b257af.jpg)
![settings](https://cloud.githubusercontent.com/assets/7813974/11865127/563b3ba0-a4a2-11e5-8bb8-0adfa17a3c79.jpg)
![areyousure](https://cloud.githubusercontent.com/assets/7813974/11865129/563f7eae-a4a2-11e5-9f47-bec97db5421d.jpg)
