### ISSUE TITLE
Implement Game Intro

### ISSUE THREAD

**Issue by emabece** [anticto/steamroll#762]
Mixing images and text boxes and widgets, create the introductory secuence of the game
![introgif](https://cloud.githubusercontent.com/assets/8545905/11928713/05400bfe-a7d6-11e5-88ce-0cc7fc06b5c4.gif)

**Comment by emabece** [comment]
These are the mockups for each page:

![1mockup](https://cloud.githubusercontent.com/assets/8545905/12329453/ba4303ea-bae0-11e5-8973-6283c0ceef8b.jpg)

![2mockup](https://cloud.githubusercontent.com/assets/8545905/12329455/bd24c792-bae0-11e5-96b2-27b926c4cfd4.jpg)

![3mockup](https://cloud.githubusercontent.com/assets/8545905/12329456/bf7cac3a-bae0-11e5-9e41-41ef4d197d5a.jpg)

**Comment by emabece** [comment]
Inside the Fonts directory the two new fonts for the intro have been uploaded.

The 'bold one' is called AbrilFatface-Regular and the 'typewriter' one is called underwood_champion

**Comment by alexei-anticto** [comment]
The intro is ready to animate in itemsMenu/Intro/IntroWidget

**Comment by emabece** [comment]
Intro animated. 
It must be implemented to play in the begining of the game (that is the first time the 1st level is run).
3 or 4 non-blocking dialogues from the main character will be inserted before, after and during the animation.

**Comment by emabece** [comment]
IntroWidget has been updated with 5 animations:
- FirstText: (1 sec) with character text box.
- Page1: (2,5 sec) first page appears, then a text box.
- Page2: (3 sec) second page appears, then a text box.
- Page3: (4 sec) final page appears, then a text box.
- ExitPages: (0.2 sec) three pages leave the screen. No text boxes.

Right after the last animation, first text in the game must appear (that is "I finally have my Scarabeus!")
