### ISSUE TITLE
Beautify Final Level

### ISSUE THREAD

**Issue by emabece** [anticto/steamroll#772]
- [x] Level art
- [x] Particle systems (ray, gravity rocks, ...)
- [x] Crystal art enhancement
- [x] Portal & Cinematic

**Comment by jordirovira** [comment]
hi ha una paret grisa darrera l'scarabeus a l'inici.

**Comment by jordirovira** [comment]
Els rajos encara tenen trams rectes: 
![image](https://cloud.githubusercontent.com/assets/7405808/12655248/5896e1a2-c5f8-11e5-9572-4399679de0bf.png)

**Comment by jordirovira** [comment]
Es pot veure el cel en la primera sala.
