### ISSUE TITLE
Crèdits

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#804]
Actualitzar els crèdits:
- [ ] cal afegir icec
- [ ] agraïments genèrics
- [ ] agraïmets personals

**Comment by jordirovira** [comment]
Cada un té la possibilitat d'afegir una part d'agraïments personals als crèdits. Apareixeran a "Special Thanks" però sense especificar de qui venen.

**Comment by jordirovira** [comment]
Em reservo el dret a vetar.

**Comment by emabece** [comment]
Gemma, Pichardo, Genís, Jenni

**Comment by alexei-anticto** [comment]
Sergi
