### ISSUE TITLE
Menu d'opcions des del menu principal illegible

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#814]
si el problema és el fons fosc, afegiu una pàgina de diari o el que sigui.

**Comment by emabece** [comment]
He canviat el requadre blanc, ara és negre. 

- [ ] A dins l'Steamlog, no fer desaparèixer el requadre negre.
- [ ] Tots els botons, icones i textos de botons que són negres/gris fosc, s'han de canviar de color pel groc clar i si fa falta un color de hover, que sigui el taronja

**Comment by alexei-anticto** [comment]
El nou disseny és difícil d'implementar correctament pq el requadre negre no encaixa bé a la vegada al menú principal i al de joc a part d'altres detalls. Com que hi portem massa temps he fet revert i ho he deixat legible, ja s'arreglarà després.
