### ISSUE TITLE
control de potència amb ratolí no es prou precís pel final del tutorial (en linux?)

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#867]
a l'intentar col-locar la paret salta molt. potser degut al framerate baix

**Comment by alexei-anticto** [comment]
L'he provat en windows i linux i va bé.

**Comment by alexei-anticto** [comment]
Framerate baix? En quina màquina?

**Comment by alexei-anticto** [comment]
En mac també funciona.

**Comment by alexei-anticto** [comment]
He millorat la precisió i tacte de la rodeta, proveu-ho @jordirovira i @emabece
