### ISSUE TITLE
Optimitzar ajuntar textures de la interfície

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#873]
- [ ] Tant la de la dreta com la de l'esquerra, posar mapes d'especular en canals alfa dels mapes de color, i AO en el canal alfa del normal map.
- [ ] Assegurar-se que no són més grans del que cal per jugar a 1080
- [ ] Si cal, pels dials que tenen icones que canvien separar aquella part en un submaterial per no haver de duplicar tota la textura per cada icona.

**Comment by alexei-anticto** [comment]
Recordeu que una vegada es van limitar totes les textures del directori UI amb el paràmetre "Maximum Texture Size" a 512. Des de llavors segurament totes les textures noves no tenen aquest paràmetre i s'hi hauria d'afegir. A més, s'hauria de decidir si aquesta mida és la correcta.
