### ISSUE TITLE
Avalua si val la pena activar un powerup de marqueting a steam.

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#914]
Encara que estiguem encara en la setmana de llançament.

**Comment by alexei-anticto** [comment]
Havent fet una mica de recerca sobre el tema, ara mateix el problema més important és la conversió entre exposicions a la pàgina principal de steam a vendes. Tot i que estem bastant per sobre de la mitjana, només els jocs moltíssim per sobre de la mitjana tenen promoció extra.

Altres problemes, com màrketing fora de steam i experiència dels que ja han comprat el joc en aquest moment no semblen tan importants.

Crec que abans de gastar una ronda de visibilitat hauríem de pensar com incrementar la conversió exposició->vendes.
