### ISSUE TITLE
Optimize tutorial level

### ISSUE THREAD

**Issue by alexei-anticto** [anticto/steamroll#926]
-Remove all invisible objects and rooms.
-Remove some spotlights with dynamic shadows.
-Maybe switch dynamic shadow spotlight from movable to stationary.

**Comment by alexei-anticto** [comment]
-Remove dynamic shadows from all meshes and reenable only for important ones such as fences and objects in the scarabeus' way.

**Comment by emabece** [comment]
- Number of objects reduced from 4116 to 2727
- One Spot light deleted
- Most of spot light radius reduced

Check the level now and if still bad performance, we'll have to check the Dynamicshadows of not important meshes

**Comment by RicardRC** [comment]
embece updated particle effect light radius and improved performance a lot
