### ISSUE TITLE
Problemes de layout amb resolucions altes

### ISSUE THREAD

**Issue by jordirovira** [anticto/steamroll#928]
<img width="1440" alt="screenshot 2016-03-12 18 27 28" src="https://cloud.githubusercontent.com/assets/7405808/13741664/ce12b638-e9d7-11e5-941b-3a3a7bb8096d.png">

**Comment by RicardRC** [comment]
![1](https://user-images.githubusercontent.com/35220750/34774454-a975eb1a-f60f-11e7-98ed-fc4fcf47a4f0.PNG)

**Comment by RicardRC** [comment]
![2](https://user-images.githubusercontent.com/35220750/34774548-099ddd36-f610-11e7-8963-8871989c951a.jpg)

**Comment by RicardRC** [comment]
![3](https://user-images.githubusercontent.com/35220750/34774560-12d39bd4-f610-11e7-9b3c-978d662da189.jpg)

**Comment by RicardRC** [comment]
![5](https://user-images.githubusercontent.com/35220750/34774567-1933f1f4-f610-11e7-8276-46eea56dc2a4.jpg)

**Comment by RicardRC** [comment]
Settings screen layout problems solved, but a flickering problem arises with the implemented solution. Inherent to UE4, solvable with a more work than we can currently give to it.
