### ISSUE TITLE
In the Driller level, the Scarabeus doesn't follow the Driller location when is docked in the Driller

### ISSUE THREAD

**Issue by emabece** [anticto/steamroll#985]

**Comment by RicardRC** [comment]
Couldn't reproduce the bug on my machine

**Comment by RicardRC** [comment]
AttachTo: '/Game/Maps/Driller/UEDPIE_0_Driller_Dinamics.Driller_Dinamics:PersistentLevel.DrillerBP_C_1.DeploymentSpot' is not static  (in blueprint "DrillerBP"), cannot attach '/Game/Maps/Driller/UEDPIE_0_Driller_Dinamics.Driller_Dinamics:PersistentLevel.DeploymentSpot_C_6063.DeploymentRadius' which is static to it. Aborting.

Shown on the original machine when the bug happens
